name: Build and publish Docker image

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        IMAGE_TAG: cexiolabs/${{ secrets.DOCKERHUB_REPO }}:$(date +%Y%m%d-%H%M%S)
        IMAGE_TAG_LATEST: cexiolabs/${{ secrets.DOCKERHUB_REPO }}:latest
      run: docker build --tag $IMAGE_TAG --tag $IMAGE_TAG_LATEST .
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish the Docker image
      run: docker push -a cexiolabs/${{ secrets.DOCKERHUB_REPO }}
